### PR TITLE
Update gui

### PR DESCRIPTION
**Pull request by sstone93**
GUI update is mostly working for the training phase (next button is still always available but I will fix that)

Some sort of weird behaviour:
- after clicking 3 emojis, it jumps back to entering images
- because of the listener type (onFocusLost) on the textfield, you have to toggle the show password check in order for the emojis to become active, i'm not sure how the user will move on in the testing mode because the checkbox will not be there to click. May need to consider a different listener type.

### CODE REVIEW

**Comment by sstone93** [comment]
I added some more logic to update:
- I think the things should be properly hidden in texting mode
- I think the label at the top should update with the password type to be entered
I say I think because this branch is behind master (due to merge conflicts) so I do not have the handler for the next button click yet. @ChantalForget if you have time and are able to fix the conflicts I would love you.

Outstanding things to do:
- add the code for disabling the next button if not enough entries(GUI only, see above re being behind master)
- add the dialog boxes for successful entry, failed entry, and ending
- Do we want to add labels indicating how many images they've clicked? if so, where? no room under emojis atm, could move button under text, maybe?
- Should the submit button be disabled until they reach the third part?

**Comment by ChantalForget** [comment]
instead of a number clicked box you could also just have a popup? if you don't have time though no worries, we can just tell the people.

I'd say the submit button should be disabled.

also fixed the conflicts :)

**Comment by ChantalForget** [comment]
Weird behaviour you see is because of me for the landscape thing. I can change that.

Instead when they click submit i'll have it change back to landscape. for some reason i had put that when they clicked 3 emojis.
should i put it in for the next button as well?

**Comment by sstone93** [comment]
I'm not quite sure what you mean by a pop up, like you want a pop up every time the user clicks a button? I think that is going to annoy users/slow down the entry.

Yes, when they click next, they are starting anew with a different password.

**Comment by ChantalForget** [comment]
that's a good point. You could put the clicks for landscape under it for now and then figure out emojis after  I guess. (or maybe put the clicks above the grids?)

**Pull request merged**
